name: okiben
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.2+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1
  provider: ^6.1.2
  shared_preferences: ^2.3.1
  settings_ui: ^2.0.2
  font_awesome_flutter: ^10.8.0
  url_launcher: ^6.3.1


flutter_native_splash:
  color: '#ffffff'   # 背景色
  image: "assets/images/icon/app_icon.png"
  # color_dark: '#262626'
  # image_dark: 'assets/images/bread.png'
  fullscreen: true
  ios_content_mode: center
  android_gravity: center
  web_image_mode: center
  android_12:
    icon_background_color: '#ffffff'
    image: "assets/images/icon/app_icon.png"
    # icon_background_color_dark: '#262626'
    # image_dark: 'assets/images/splash_android12.png'



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/bread.png
    - assets/images/big_image_sample.png
    - assets/images/switch/switch_on.png
    - assets/images/switch/switch_off.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
        #   style: Bold
        # - asset: assets/fonts/poppins/Poppins-Medium.ttf
        #   style: Medium
        # - asset: assets/fonts/poppins/Poppins-Regular.ttf
        #   style: Regular
        # - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
        #   style: SemiBold
    - family: Kosugi
      fonts:
        - asset: assets/fonts/Kosugi/Kosugi-Regular.ttf
    - family: IBM_Plex_Sans_JP
      fonts:
        - asset: assets/fonts/IBM_Plex_Sans_JP/IBMPlexSansJP-Regular.ttf


# アプリアイコン
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon/app_icon.png"